= Stevedore
Marat Radchenko
:slug: slonopotamus/stevedore
:uri-project: https://github.com/{slug}
:uri-ci: {uri-project}/actions?query=branch%3Amain

image:https://img.shields.io/github/release/{slug}.svg[Download,link={uri-project}/releases/latest]
image:{uri-project}/workflows/CI/badge.svg?branch=master[Build Status,link={uri-ci}]

== Overview

This project aims to be a frictionless Docker distribution for Windows.

Stevedore currently only supports Windows containers.

== Installation

=== Chocolatey

Stevedore is available via https://community.chocolatey.org/packages/stevedore[Chocolatey] package manager.
If you already have Chocolatey installed, you can just run the following command from elevated console:

```
choco install stevedore
```

Note that reboot is required before you can use `docker` commands.

=== Manual

. Download {uri-project}/releases/latest[MSI installer]
. Double-click on it
. Next-next-next
. Reboot your computer.
This is needed to finish installation of Windows Containers feature and to add your user to `docker-users` group so user can access Docker service.
. Profit! `docker` command is now available on your PATH and `dockerd` service is already running.
