= Stevedore
Marat Radchenko
:slug: slonopotamus/stevedore
:uri-project: https://github.com/{slug}
:uri-ci: {uri-project}/actions?query=branch%3Amain

image:{uri-project}/workflows/CI/badge.svg?branch=main[Build Status,link={uri-ci}]
image:https://img.shields.io/github/release/{slug}.svg[Download,link={uri-project}/releases/latest]
image:https://img.shields.io/chocolatey/v/stevedore[Chocolatey package,link=https://community.chocolatey.org/packages/stevedore]

== Overview

This project aims to be a frictionless Docker distribution for Windows.

Stevedore currently only supports Windows containers.

== Installation

=== Chocolatey

Stevedore is available via https://community.chocolatey.org/packages/stevedore[Chocolatey] package manager.
If you already have Chocolatey installed, you can just run the following command from elevated console:

[source,bash]
----
choco install stevedore
----

Note that reboot is required before you can use `docker` commands.

=== Manual

. Download {uri-project}/releases/latest[MSI installer]
. Double-click on it
. Next-next-next
. Reboot your computer.
This is needed to finish installation of Windows Containers feature and to add your user to `docker-users` group so user can access Docker service.
. Profit! `docker` command is now available on your PATH and `dockerd` service is already running.

== Bundled components

* Docker Engine 20.10.12
* Docker App 0.9.1-beta3
* Buildx 0.7.1
* Docker Compose 2.2.2
* Docker Scan 0.16.0

== Usage

After installation and reboot, `docker` command should be available on PATH.

=== Docker Compose

Stevedore installs two flavors of Docker Compose.

You can use Docker Compose V2 via `docker compose` command.

You can also use Docker Compose V1 compatibility mode via `docker-compose` command.
