= Stevedore
Marat Radchenko
:slug: slonopotamus/stevedore
:uri-project: https://github.com/{slug}
:uri-ci: {uri-project}/actions?query=branch%3Amain

image:{uri-project}/workflows/CI/badge.svg?branch=main[Build Status,link={uri-ci}]
image:https://img.shields.io/github/release/{slug}.svg[Download,link={uri-project}/releases/latest]
image:https://img.shields.io/chocolatey/v/stevedore[Chocolatey package,link=https://community.chocolatey.org/packages/stevedore]

== Overview

This project aims to be a frictionless Docker distribution for Windows.

Stevedore can be used as a replacement for `DockerMsftProvider`, Docker Desktop or Mirantis Container Runtime.

Only Windows containers are supported currently. Linux containers support is https://github.com/slonopotamus/stevedore/issues/8[under development].

== Supported OSes

* Windows 10, 11
* Windows Server 2016, 2019, 2022

== Installation

=== Chocolatey

Stevedore is available via https://community.chocolatey.org/packages/stevedore[Chocolatey] package manager.
If you already have Chocolatey installed, you can just run the following command from elevated console:

[source,bash]
----
choco install stevedore
----

Note that reboot is required before you can use `docker` commands.

=== WinGet

https://github.com/slonopotamus/stevedore/issues/15[Planned], but not available yet.

=== Manual

. Download {uri-project}/releases/latest[MSI installer]
. Double-click on it
. Next-next-next
. Reboot your computer.
This is needed to finish installation of Windows Containers feature and to add your user to `docker-users` group so user can access Docker service.
. Profit! `docker` command is now available on your PATH and `dockerd` service is already running.

== Bundled components

* Docker Engine 20.10.12
* Docker App 0.9.1-beta3
* Buildx 0.7.1
* Docker Compose 2.2.2
* Docker Scan 0.16.0

== Usage

After installation and reboot, `docker` command should be available on PATH and ready to use.

Just try `docker run hello-world` from a command line.

=== Docker Compose

Stevedore installs two flavors of Docker Compose.

You can use Docker Compose V2 via `docker compose` command.

You can also use Docker Compose V1 compatibility mode via `docker-compose` command.

== Building from source

. https://www.rust-lang.org/tools/install[Install Rust]
. Install https://wixtoolset.org/releases/https://wixtoolset.org/releases/[WiX Toolset] either manually or by running `choco install wixtoolset` if you have https://chocolatey.org/[Chocolatey]
. Clone Stevedore Git repository
. Run `cargo install cargo-wix` to install https://github.com/volks73/cargo-wix[cargo-wix]
. Run `cargo wix --nocapture` in repository root. Ready-to-use MSI package will be built in `<repo>/target/wix` directory.
