name: Stevedore fails to work properly after installation finished
description: Report an issue that happens after Stevedore was installed
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: Before reporting a bug, please check that is isn't fixed in the [latest release](https://github.com/slonopotamus/stevedore/releases/latest)
  - type: dropdown
    id: version
    attributes:
      label: Stevedore Version
      description: What Stevedore version are you using?
      options:
        - 0.8.0
        - 0.7.0
        - 0.6.1
        - 0.6.0
        - 0.5.0
        - 0.4.1
        - 0.4.0
        - 0.3.4
        - 0.3.3
        - 0.3.2
        - 0.3.1
        - 0.3.0
        - 0.2.0
        - 0.1.1
        - 0.1.0
        - 0.0.7
        - 0.0.6
        - 0.0.5
        - 0.0.4
        - 0.0.3
        - 0.0.2
        - 0.0.1
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: What steps are needed to reproduce the behavior?
      description: Describe step-by-step actions required to reproduce the issue
      placeholder: |
        1. Do this
        2. Do that
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What you expected?
      description: Describe what you expectex to happen
      placeholder: Stevedore frobs
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: What happened?
      description: Describe actual behavior that you're seeing
      placeholder: Stevedore doesn't frob and produces an error
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any additional information you think is relevant to the issue
